In [3]:
import numpy as np

In [12]:
a1 = np.arange(1, 6)
a2 = np.arange(6, 11)

In [13]:
add = a1 + a2

In [14]:
add

array([ 7,  9, 11, 13, 15])

In [15]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [16]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [17]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [19]:
a2 // a1

array([6, 3, 2, 2, 2])

In [20]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [21]:
# Broadcasting

In [23]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr + 10        # This is broadcasting 

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [26]:
matrix = arr.reshape(2,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
matrix + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [28]:
matrix * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [29]:
# deep and shallow copy

In [30]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
slice = arr[:5]        # this is shallow copy in list it will be deep copy
slice

array([1, 2, 3, 4, 5])

In [36]:
slice = slice * 10     
slice

array([10, 20, 30, 40, 50])

In [37]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
list = [1,2,3,4,5,6,7,8]
s = list[:4]
s

[1, 2, 3, 4]

In [39]:
s[3] *= 10
s

[1, 2, 3, 40]

In [40]:
list

[1, 2, 3, 4, 5, 6, 7, 8]

In [41]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

In [42]:
mat1

array([[1, 2],
       [3, 4]])

In [44]:
mat1 * mat2

array([[ 5, 12],
       [21, 32]])

In [45]:
mat1 @ mat2       # matrix multiplication

array([[19, 22],
       [43, 50]])

In [46]:
np.dot(mat1, mat2)

array([[19, 22],
       [43, 50]])

In [47]:
mat1.T           # transpose

array([[1, 3],
       [2, 4]])

In [48]:
# stacking array

In [49]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [59]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [60]:
np.hstack((arr1, arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
np.column_stack((arr1, arr2))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [62]:
# splitting

In [64]:
mat = np.arange(16).reshape(4, 4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
np.split(mat, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [69]:
np.hsplit(mat, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [73]:
np.vsplit(mat, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]