In [1]:
import numpy as np

In [3]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[4]

np.int64(15)

In [5]:
arr[-2]

np.int64(19)

In [7]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[2:8]

array([13, 14, 15, 16, 17, 18])

In [10]:
arr[6:]

array([17, 18, 19, 20])

In [12]:
arr[:4]

array([11, 12, 13, 14])

In [15]:
arr[:12000000000000]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
arr[1::4]

array([12, 16, 20])

In [18]:
matrix = np.arange(1,31).reshape(5,6)
matrix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [19]:
matrix[0]

array([1, 2, 3, 4, 5, 6])

In [20]:
matrix[3]

array([19, 20, 21, 22, 23, 24])

In [24]:
# matrix[0][1]
matrix[0,1]

np.int64(2)

In [25]:
matrix[1, 5]

np.int64(12)

In [26]:
matrix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [29]:
matrix[0:2, 2:4]

array([[ 3,  4],
       [ 9, 10]])

In [34]:
matrix[2:,4:]

array([[17, 18],
       [23, 24],
       [29, 30]])

In [33]:
matrix[:, 2]

array([ 3,  9, 15, 21, 27])

In [35]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [38]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [58]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
bool_array = np.array([True, True, True, False, False, True, True, False, True, False])
bool_array

array([ True,  True,  True, False, False,  True,  True, False,  True,
       False])

In [60]:
arr[bool_array]

array([1, 2, 3, 6, 7, 9])

In [59]:
arr.shape

(10,)

In [51]:
bool_array.shape

(10,)

In [56]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [57]:
arr1.shape

(6,)