In [3]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [8]:
l = [1,2,3,4,5]
l

[1, 2, 3, 4, 5]

In [9]:
l = [1,2,"akash", True, 10.2]
l

[1, 2, 'akash', True, 10.2]

In [10]:
arr = np.array(l)
arr

array(['1', '2', 'akash', 'True', '10.2'], dtype='<U32')

In [12]:
arr = np.array([1,2,3.4,True])
arr

array([1. , 2. , 3.4, 1. ])

In [13]:
l = [[1,2,3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
matrix = np.array(l)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

After 2d array everything above like 3d, 4d are tensor

In [19]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [22]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
arr = np.linspace(1, 10)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [29]:
arr = np.linspace(1, 5, 3)
arr

array([1., 3., 5.])

In [9]:
arr = np.linspace(1, 10, 50)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [12]:
# This is standarization =>  values are 0 to 1
arr = np.random.rand(7)
arr

array([0.04669965, 0.39347181, 0.31581225, 0.02925845, 0.20375739,
       0.76602534, 0.5093397 ])

In [20]:
# This is standarization =>  values are -3 to 3
arr = np.random.randn(10)
arr

array([-0.69821292, -0.43685435, -2.35588498,  0.59702154, -0.2393568 ,
        1.23592377,  0.70261357,  1.86364863,  0.96848606,  0.31244534])

In [25]:
n = np.random.randint(10)
n

9

In [17]:
n = np.random.randint(1, 10)
n

4

In [26]:
arr = np.random.randint(1, 10, 10)
arr

array([4, 5, 9, 6, 4, 6, 1, 9, 6, 9], dtype=int32)

In [29]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
matrix.shape

(3, 3)

In [31]:
matrix.size

9

In [32]:
matrix.dtype

dtype('int64')

In [33]:
arr

array([4, 5, 9, 6, 4, 6, 1, 9, 6, 9], dtype=int32)

In [34]:
arr.min()

np.int32(1)

In [35]:
arr.max()

np.int32(9)

In [36]:
arr.sum()

np.int64(59)

In [37]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
matrix.sum()   # This are by python not numpy

np.int64(45)

In [40]:
np.sum(matrix, axis = 0)

array([12, 15, 18])

In [41]:
np.sum(matrix, axis = 1)

array([ 6, 15, 24])

In [42]:
matrix.mean()

np.float64(5.0)

In [43]:
arr.mean()

np.float64(5.9)

In [44]:
arr.std()       # stndard deviation

np.float64(2.4677925358506134)

In [45]:
arr

array([4, 5, 9, 6, 4, 6, 1, 9, 6, 9], dtype=int32)

In [46]:
arr.argmax()       # max element index

np.int64(2)

In [47]:
arr.argmin()       # min element index

np.int64(6)

In [48]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [53]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [54]:
arr.reshape(5, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])